SELECT SUPPLIER.SUPPLIER_NAME, PART.PRICE
FROM SUPPLIER
JOIN SUPPLY ON SUPPLIER.SUPPLIER_CODE = SUPPLY.CODE_SUPPLIER
JOIN PART ON SUPPLY.CODE_PIECE = PART.CODE_PART
JOIN CAR ON SUPPLY.CODE_CAR = CAR.CODE_CAR
WHERE SUPPLIER.CITY = 'VITORIA' AND PART.CODE_PART = 'MOTOR' AND CAR.CODE_CAR = 'KOMBI';